### ISSUE TITLE
Parsing error when trying to parse the diesel table macro

### ISSUE THREAD

**Issue by weiznich** [lukaslueg/macro_railroad#13] opened 2018-08-16 08:21 UTC
I've tried to paste the [(internal) diesel table marco](https://github.com/diesel-rs/diesel/blob/master/diesel/src/macros/mod.rs#L293-L450) into the web demo.
This fails with the following error:
```
Failed to parse, and I didn't even write an error-handler. Anyway:
ParseError(None)
```

The issue seems to be with the following rule:
```rust
macro_rules! __diesel_parse_table {
    // Found an import
    (
        tokens = [use $($import:tt)::+; $($rest:tt)*],
        imports = [$($imports:tt)*],
        $($args:tt)*
    ) => {
        __diesel_parse_table! {
            tokens = [$($rest)*],
            imports = [$($imports)* use $($import)::+;],
            $($args)*
        }
    };
}
```

**Comment by dtolnay** [comment] 2018-08-16 08:27
Looks like a duplicate of #8.

**Comment by lukaslueg** [comment] 2018-08-16 19:46
Will track this in #8

**Comment by lukaslueg** [comment] 2018-08-16 19:47
Thanks for the report ;-)

**Closed by lukaslueg** 2018-08-16 19:46 UTC
